INSERT INTO `single_meal`(  `sm_id`, 
							`sm_no`, 
							`sm_title`, 
							`sm_client_id`, 
							`sm_trainer_id`, 
							`sm_date`, 
							`sm_calories`, 
							`sm_proteins`, 
							`sm_carbs`, 
							`sm_fats`) 
							
				  VALUES (  :sm_id, 
							:sm_no, 
							:sm_title, 
							:sm_client_id, 
							:sm_trainer_id, 
							:sm_date,
							:sm_calories, 
							:sm_proteins, 
							:sm_carbs, 
							:sm_fats) 