INSERT INTO `user`( `usr_username`, 
				    `usr_firstname`, 
				    `usr_lastname`, 
				    `usr_email`, 
				    `usr_is_trainer`, 
				    `usr_password`, 
					`usr_age`, 
					`usr_weight`, 
					`usr_height`, 
					`usr_phone`, 
					`usr_goal`, 
					`usr_description`) 
VALUES ( :usr_username,
  	 	 :usr_firstname,
		 :usr_lastname,
		 :usr_email,
		 :usr_is_trainer,
		 :usr_password,
		 :usr_age,
		 :usr_weight,
		 :usr_height,
		 :usr_phone,
		 :usr_goal,
		 :usr_description)